---
# handlers file for /etc/ansible/roles/httpd
#- name: Restart samba
#  service: name=samba state=restarted
#- name: restart nfs
#  service: name=nfs state=restarted
#- name: restart httpd
#  service:
#    name: httpd
#    state: restarted
